# flex-odbc Sidecar Discovery Configuration
# Path is relative to the s library or absolute
implementation.cmd=.\samples\csharp_sample\bin\Release\net8.0\win-x64\publish\Sidecar.exe
protocol.type=protobuf
ipc.mode=pipe

