# flex-odbc Sidecar Discovery Configuration
# Path is relative to the s library or absolute
implementation.cmd=java -jar ../samples/java_sample/target/java-sidecar-1.0-SNAPSHOT.jar
protocol.type=protobuf
ipc.mode=pipe
