// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public interface ConnectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flexodbc.ConnectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string connection_string = 1;</code>
   * @return The connectionString.
   */
  java.lang.String getConnectionString();
  /**
   * <code>string connection_string = 1;</code>
   * @return The bytes for connectionString.
   */
  com.google.protobuf.ByteString
      getConnectionStringBytes();
}
