// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public interface DisconnectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flexodbc.DisconnectRequest)
    com.google.protobuf.MessageOrBuilder {
}
