// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public interface DriverConnectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flexodbc.DriverConnectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string sql_state = 2;</code>
   * @return The sqlState.
   */
  java.lang.String getSqlState();
  /**
   * <code>string sql_state = 2;</code>
   * @return The bytes for sqlState.
   */
  com.google.protobuf.ByteString
      getSqlStateBytes();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
