// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public final class Driver extends com.google.protobuf.GeneratedFile {
  private Driver() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Driver");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_RowSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_RowSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_Row_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_ConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_ConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_ConnectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_ConnectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_DriverConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_DriverConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_DriverConnectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_DriverConnectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_ExecuteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_ExecuteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_FetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_FetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_FetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_FetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_DisconnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_DisconnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flexodbc_DisconnectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_flexodbc_DisconnectResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014driver.proto\022\010flexodbc\"a\n\006RowSet\022\033\n\004ro" +
      "ws\030\001 \003(\0132\r.flexodbc.Row\022\020\n\010has_more\030\002 \001(" +
      "\010\022\021\n\tsql_state\030\003 \001(\t\022\025\n\rerror_message\030\004 " +
      "\001(\t\"\026\n\003Row\022\017\n\007columns\030\001 \003(\014\"+\n\016ConnectRe" +
      "quest\022\031\n\021connection_string\030\001 \001(\t\"L\n\017Conn" +
      "ectResponse\022\017\n\007success\030\001 \001(\010\022\021\n\tsql_stat" +
      "e\030\002 \001(\t\022\025\n\rerror_message\030\003 \001(\t\"1\n\024Driver" +
      "ConnectRequest\022\031\n\021connection_string\030\001 \001(" +
      "\t\"R\n\025DriverConnectResponse\022\017\n\007success\030\001 " +
      "\001(\010\022\021\n\tsql_state\030\002 \001(\t\022\025\n\rerror_message\030" +
      "\003 \001(\t\"1\n\016ExecuteRequest\022\r\n\005query\030\001 \001(\t\022\020" +
      "\n\010max_rows\030\002 \001(\005\"K\n\017ExecuteResponse\022\017\n\007s" +
      "uccess\030\001 \001(\010\022\'\n\rinitial_batch\030\002 \001(\0132\020.fl" +
      "exodbc.RowSet\" \n\014FetchRequest\022\020\n\010max_row" +
      "s\030\001 \001(\005\"0\n\rFetchResponse\022\037\n\005batch\030\001 \001(\0132" +
      "\020.flexodbc.RowSet\"\023\n\021DisconnectRequest\"%" +
      "\n\022DisconnectResponse\022\017\n\007success\030\001 \001(\010B7\n" +
      "\032com.flexodbc.sidecar.protoP\001\252\002\026FlexOdbc" +
      ".Sidecar.Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_flexodbc_RowSet_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_flexodbc_RowSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_RowSet_descriptor,
        new java.lang.String[] { "Rows", "HasMore", "SqlState", "ErrorMessage", });
    internal_static_flexodbc_Row_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_flexodbc_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_Row_descriptor,
        new java.lang.String[] { "Columns", });
    internal_static_flexodbc_ConnectRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_flexodbc_ConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_ConnectRequest_descriptor,
        new java.lang.String[] { "ConnectionString", });
    internal_static_flexodbc_ConnectResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_flexodbc_ConnectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_ConnectResponse_descriptor,
        new java.lang.String[] { "Success", "SqlState", "ErrorMessage", });
    internal_static_flexodbc_DriverConnectRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_flexodbc_DriverConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_DriverConnectRequest_descriptor,
        new java.lang.String[] { "ConnectionString", });
    internal_static_flexodbc_DriverConnectResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_flexodbc_DriverConnectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_DriverConnectResponse_descriptor,
        new java.lang.String[] { "Success", "SqlState", "ErrorMessage", });
    internal_static_flexodbc_ExecuteRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_flexodbc_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_ExecuteRequest_descriptor,
        new java.lang.String[] { "Query", "MaxRows", });
    internal_static_flexodbc_ExecuteResponse_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_flexodbc_ExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_ExecuteResponse_descriptor,
        new java.lang.String[] { "Success", "InitialBatch", });
    internal_static_flexodbc_FetchRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_flexodbc_FetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_FetchRequest_descriptor,
        new java.lang.String[] { "MaxRows", });
    internal_static_flexodbc_FetchResponse_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_flexodbc_FetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_FetchResponse_descriptor,
        new java.lang.String[] { "Batch", });
    internal_static_flexodbc_DisconnectRequest_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_flexodbc_DisconnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_DisconnectRequest_descriptor,
        new java.lang.String[] { });
    internal_static_flexodbc_DisconnectResponse_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_flexodbc_DisconnectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_flexodbc_DisconnectResponse_descriptor,
        new java.lang.String[] { "Success", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
