// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

/**
 * Protobuf type {@code flexodbc.DriverConnectRequest}
 */
@com.google.protobuf.Generated
public final class DriverConnectRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flexodbc.DriverConnectRequest)
    DriverConnectRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "DriverConnectRequest");
  }
  // Use DriverConnectRequest.newBuilder() to construct.
  private DriverConnectRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DriverConnectRequest() {
    connectionString_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_DriverConnectRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_DriverConnectRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_DriverConnectRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.flexodbc.sidecar.proto.DriverConnectRequest.class, com.flexodbc.sidecar.proto.DriverConnectRequest.Builder.class);
  }

  public static final int CONNECTION_STRING_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object connectionString_ = "";
  /**
   * <code>string connection_string = 1;</code>
   * @return The connectionString.
   */
  @java.lang.Override
  public java.lang.String getConnectionString() {
    java.lang.Object ref = connectionString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      connectionString_ = s;
      return s;
    }
  }
  /**
   * <code>string connection_string = 1;</code>
   * @return The bytes for connectionString.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConnectionStringBytes() {
    java.lang.Object ref = connectionString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      connectionString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(connectionString_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, connectionString_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(connectionString_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, connectionString_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.flexodbc.sidecar.proto.DriverConnectRequest)) {
      return super.equals(obj);
    }
    com.flexodbc.sidecar.proto.DriverConnectRequest other = (com.flexodbc.sidecar.proto.DriverConnectRequest) obj;

    if (!getConnectionString()
        .equals(other.getConnectionString())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONNECTION_STRING_FIELD_NUMBER;
    hash = (53 * hash) + getConnectionString().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.flexodbc.sidecar.proto.DriverConnectRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.flexodbc.sidecar.proto.DriverConnectRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flexodbc.DriverConnectRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flexodbc.DriverConnectRequest)
      com.flexodbc.sidecar.proto.DriverConnectRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_DriverConnectRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_DriverConnectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.flexodbc.sidecar.proto.DriverConnectRequest.class, com.flexodbc.sidecar.proto.DriverConnectRequest.Builder.class);
    }

    // Construct using com.flexodbc.sidecar.proto.DriverConnectRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      connectionString_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_DriverConnectRequest_descriptor;
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.DriverConnectRequest getDefaultInstanceForType() {
      return com.flexodbc.sidecar.proto.DriverConnectRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.DriverConnectRequest build() {
      com.flexodbc.sidecar.proto.DriverConnectRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.DriverConnectRequest buildPartial() {
      com.flexodbc.sidecar.proto.DriverConnectRequest result = new com.flexodbc.sidecar.proto.DriverConnectRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.flexodbc.sidecar.proto.DriverConnectRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.connectionString_ = connectionString_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.flexodbc.sidecar.proto.DriverConnectRequest) {
        return mergeFrom((com.flexodbc.sidecar.proto.DriverConnectRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.flexodbc.sidecar.proto.DriverConnectRequest other) {
      if (other == com.flexodbc.sidecar.proto.DriverConnectRequest.getDefaultInstance()) return this;
      if (!other.getConnectionString().isEmpty()) {
        connectionString_ = other.connectionString_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              connectionString_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object connectionString_ = "";
    /**
     * <code>string connection_string = 1;</code>
     * @return The connectionString.
     */
    public java.lang.String getConnectionString() {
      java.lang.Object ref = connectionString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connectionString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string connection_string = 1;</code>
     * @return The bytes for connectionString.
     */
    public com.google.protobuf.ByteString
        getConnectionStringBytes() {
      java.lang.Object ref = connectionString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectionString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string connection_string = 1;</code>
     * @param value The connectionString to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionString(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      connectionString_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string connection_string = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionString() {
      connectionString_ = getDefaultInstance().getConnectionString();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string connection_string = 1;</code>
     * @param value The bytes for connectionString to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      connectionString_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:flexodbc.DriverConnectRequest)
  }

  // @@protoc_insertion_point(class_scope:flexodbc.DriverConnectRequest)
  private static final com.flexodbc.sidecar.proto.DriverConnectRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.flexodbc.sidecar.proto.DriverConnectRequest();
  }

  public static com.flexodbc.sidecar.proto.DriverConnectRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DriverConnectRequest>
      PARSER = new com.google.protobuf.AbstractParser<DriverConnectRequest>() {
    @java.lang.Override
    public DriverConnectRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DriverConnectRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DriverConnectRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.flexodbc.sidecar.proto.DriverConnectRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

