// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

/**
 * Protobuf type {@code flexodbc.ExecuteResponse}
 */
@com.google.protobuf.Generated
public final class ExecuteResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flexodbc.ExecuteResponse)
    ExecuteResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ExecuteResponse");
  }
  // Use ExecuteResponse.newBuilder() to construct.
  private ExecuteResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExecuteResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_ExecuteResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_ExecuteResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_ExecuteResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.flexodbc.sidecar.proto.ExecuteResponse.class, com.flexodbc.sidecar.proto.ExecuteResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int INITIAL_BATCH_FIELD_NUMBER = 2;
  private com.flexodbc.sidecar.proto.RowSet initialBatch_;
  /**
   * <code>.flexodbc.RowSet initial_batch = 2;</code>
   * @return Whether the initialBatch field is set.
   */
  @java.lang.Override
  public boolean hasInitialBatch() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.flexodbc.RowSet initial_batch = 2;</code>
   * @return The initialBatch.
   */
  @java.lang.Override
  public com.flexodbc.sidecar.proto.RowSet getInitialBatch() {
    return initialBatch_ == null ? com.flexodbc.sidecar.proto.RowSet.getDefaultInstance() : initialBatch_;
  }
  /**
   * <code>.flexodbc.RowSet initial_batch = 2;</code>
   */
  @java.lang.Override
  public com.flexodbc.sidecar.proto.RowSetOrBuilder getInitialBatchOrBuilder() {
    return initialBatch_ == null ? com.flexodbc.sidecar.proto.RowSet.getDefaultInstance() : initialBatch_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getInitialBatch());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInitialBatch());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.flexodbc.sidecar.proto.ExecuteResponse)) {
      return super.equals(obj);
    }
    com.flexodbc.sidecar.proto.ExecuteResponse other = (com.flexodbc.sidecar.proto.ExecuteResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (hasInitialBatch() != other.hasInitialBatch()) return false;
    if (hasInitialBatch()) {
      if (!getInitialBatch()
          .equals(other.getInitialBatch())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (hasInitialBatch()) {
      hash = (37 * hash) + INITIAL_BATCH_FIELD_NUMBER;
      hash = (53 * hash) + getInitialBatch().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.flexodbc.sidecar.proto.ExecuteResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.flexodbc.sidecar.proto.ExecuteResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.flexodbc.sidecar.proto.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.flexodbc.sidecar.proto.ExecuteResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flexodbc.ExecuteResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flexodbc.ExecuteResponse)
      com.flexodbc.sidecar.proto.ExecuteResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_ExecuteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.flexodbc.sidecar.proto.ExecuteResponse.class, com.flexodbc.sidecar.proto.ExecuteResponse.Builder.class);
    }

    // Construct using com.flexodbc.sidecar.proto.ExecuteResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetInitialBatchFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      initialBatch_ = null;
      if (initialBatchBuilder_ != null) {
        initialBatchBuilder_.dispose();
        initialBatchBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.ExecuteResponse getDefaultInstanceForType() {
      return com.flexodbc.sidecar.proto.ExecuteResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.ExecuteResponse build() {
      com.flexodbc.sidecar.proto.ExecuteResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.ExecuteResponse buildPartial() {
      com.flexodbc.sidecar.proto.ExecuteResponse result = new com.flexodbc.sidecar.proto.ExecuteResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.flexodbc.sidecar.proto.ExecuteResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.initialBatch_ = initialBatchBuilder_ == null
            ? initialBatch_
            : initialBatchBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.flexodbc.sidecar.proto.ExecuteResponse) {
        return mergeFrom((com.flexodbc.sidecar.proto.ExecuteResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.flexodbc.sidecar.proto.ExecuteResponse other) {
      if (other == com.flexodbc.sidecar.proto.ExecuteResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.hasInitialBatch()) {
        mergeInitialBatch(other.getInitialBatch());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetInitialBatchFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private com.flexodbc.sidecar.proto.RowSet initialBatch_;
    private com.google.protobuf.SingleFieldBuilder<
        com.flexodbc.sidecar.proto.RowSet, com.flexodbc.sidecar.proto.RowSet.Builder, com.flexodbc.sidecar.proto.RowSetOrBuilder> initialBatchBuilder_;
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     * @return Whether the initialBatch field is set.
     */
    public boolean hasInitialBatch() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     * @return The initialBatch.
     */
    public com.flexodbc.sidecar.proto.RowSet getInitialBatch() {
      if (initialBatchBuilder_ == null) {
        return initialBatch_ == null ? com.flexodbc.sidecar.proto.RowSet.getDefaultInstance() : initialBatch_;
      } else {
        return initialBatchBuilder_.getMessage();
      }
    }
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     */
    public Builder setInitialBatch(com.flexodbc.sidecar.proto.RowSet value) {
      if (initialBatchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        initialBatch_ = value;
      } else {
        initialBatchBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     */
    public Builder setInitialBatch(
        com.flexodbc.sidecar.proto.RowSet.Builder builderForValue) {
      if (initialBatchBuilder_ == null) {
        initialBatch_ = builderForValue.build();
      } else {
        initialBatchBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     */
    public Builder mergeInitialBatch(com.flexodbc.sidecar.proto.RowSet value) {
      if (initialBatchBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          initialBatch_ != null &&
          initialBatch_ != com.flexodbc.sidecar.proto.RowSet.getDefaultInstance()) {
          getInitialBatchBuilder().mergeFrom(value);
        } else {
          initialBatch_ = value;
        }
      } else {
        initialBatchBuilder_.mergeFrom(value);
      }
      if (initialBatch_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     */
    public Builder clearInitialBatch() {
      bitField0_ = (bitField0_ & ~0x00000002);
      initialBatch_ = null;
      if (initialBatchBuilder_ != null) {
        initialBatchBuilder_.dispose();
        initialBatchBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     */
    public com.flexodbc.sidecar.proto.RowSet.Builder getInitialBatchBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetInitialBatchFieldBuilder().getBuilder();
    }
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     */
    public com.flexodbc.sidecar.proto.RowSetOrBuilder getInitialBatchOrBuilder() {
      if (initialBatchBuilder_ != null) {
        return initialBatchBuilder_.getMessageOrBuilder();
      } else {
        return initialBatch_ == null ?
            com.flexodbc.sidecar.proto.RowSet.getDefaultInstance() : initialBatch_;
      }
    }
    /**
     * <code>.flexodbc.RowSet initial_batch = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.flexodbc.sidecar.proto.RowSet, com.flexodbc.sidecar.proto.RowSet.Builder, com.flexodbc.sidecar.proto.RowSetOrBuilder> 
        internalGetInitialBatchFieldBuilder() {
      if (initialBatchBuilder_ == null) {
        initialBatchBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.flexodbc.sidecar.proto.RowSet, com.flexodbc.sidecar.proto.RowSet.Builder, com.flexodbc.sidecar.proto.RowSetOrBuilder>(
                getInitialBatch(),
                getParentForChildren(),
                isClean());
        initialBatch_ = null;
      }
      return initialBatchBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:flexodbc.ExecuteResponse)
  }

  // @@protoc_insertion_point(class_scope:flexodbc.ExecuteResponse)
  private static final com.flexodbc.sidecar.proto.ExecuteResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.flexodbc.sidecar.proto.ExecuteResponse();
  }

  public static com.flexodbc.sidecar.proto.ExecuteResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteResponse>() {
    @java.lang.Override
    public ExecuteResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.flexodbc.sidecar.proto.ExecuteResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

