// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public interface ExecuteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flexodbc.ExecuteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <pre>
   * Batch size requested by C++ host
   * </pre>
   *
   * <code>int32 max_rows = 2;</code>
   * @return The maxRows.
   */
  int getMaxRows();
}
