// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public interface ExecuteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flexodbc.ExecuteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>.flexodbc.RowSet initial_batch = 2;</code>
   * @return Whether the initialBatch field is set.
   */
  boolean hasInitialBatch();
  /**
   * <code>.flexodbc.RowSet initial_batch = 2;</code>
   * @return The initialBatch.
   */
  com.flexodbc.sidecar.proto.RowSet getInitialBatch();
  /**
   * <code>.flexodbc.RowSet initial_batch = 2;</code>
   */
  com.flexodbc.sidecar.proto.RowSetOrBuilder getInitialBatchOrBuilder();
}
