// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public interface FetchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flexodbc.FetchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.flexodbc.RowSet batch = 1;</code>
   * @return Whether the batch field is set.
   */
  boolean hasBatch();
  /**
   * <code>.flexodbc.RowSet batch = 1;</code>
   * @return The batch.
   */
  com.flexodbc.sidecar.proto.RowSet getBatch();
  /**
   * <code>.flexodbc.RowSet batch = 1;</code>
   */
  com.flexodbc.sidecar.proto.RowSetOrBuilder getBatchOrBuilder();
}
