// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

/**
 * <pre>
 * Emulates a streaming Fetch RPC over standard IPC pipe
 * </pre>
 *
 * Protobuf type {@code flexodbc.FetchResponse}
 */
@com.google.protobuf.Generated
public final class FetchResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flexodbc.FetchResponse)
    FetchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "FetchResponse");
  }
  // Use FetchResponse.newBuilder() to construct.
  private FetchResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FetchResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_FetchResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_FetchResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_FetchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.flexodbc.sidecar.proto.FetchResponse.class, com.flexodbc.sidecar.proto.FetchResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BATCH_FIELD_NUMBER = 1;
  private com.flexodbc.sidecar.proto.RowSet batch_;
  /**
   * <code>.flexodbc.RowSet batch = 1;</code>
   * @return Whether the batch field is set.
   */
  @java.lang.Override
  public boolean hasBatch() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.flexodbc.RowSet batch = 1;</code>
   * @return The batch.
   */
  @java.lang.Override
  public com.flexodbc.sidecar.proto.RowSet getBatch() {
    return batch_ == null ? com.flexodbc.sidecar.proto.RowSet.getDefaultInstance() : batch_;
  }
  /**
   * <code>.flexodbc.RowSet batch = 1;</code>
   */
  @java.lang.Override
  public com.flexodbc.sidecar.proto.RowSetOrBuilder getBatchOrBuilder() {
    return batch_ == null ? com.flexodbc.sidecar.proto.RowSet.getDefaultInstance() : batch_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBatch());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBatch());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.flexodbc.sidecar.proto.FetchResponse)) {
      return super.equals(obj);
    }
    com.flexodbc.sidecar.proto.FetchResponse other = (com.flexodbc.sidecar.proto.FetchResponse) obj;

    if (hasBatch() != other.hasBatch()) return false;
    if (hasBatch()) {
      if (!getBatch()
          .equals(other.getBatch())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBatch()) {
      hash = (37 * hash) + BATCH_FIELD_NUMBER;
      hash = (53 * hash) + getBatch().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.flexodbc.sidecar.proto.FetchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.flexodbc.sidecar.proto.FetchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.flexodbc.sidecar.proto.FetchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.flexodbc.sidecar.proto.FetchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Emulates a streaming Fetch RPC over standard IPC pipe
   * </pre>
   *
   * Protobuf type {@code flexodbc.FetchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flexodbc.FetchResponse)
      com.flexodbc.sidecar.proto.FetchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_FetchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_FetchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.flexodbc.sidecar.proto.FetchResponse.class, com.flexodbc.sidecar.proto.FetchResponse.Builder.class);
    }

    // Construct using com.flexodbc.sidecar.proto.FetchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBatchFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      batch_ = null;
      if (batchBuilder_ != null) {
        batchBuilder_.dispose();
        batchBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_FetchResponse_descriptor;
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.FetchResponse getDefaultInstanceForType() {
      return com.flexodbc.sidecar.proto.FetchResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.FetchResponse build() {
      com.flexodbc.sidecar.proto.FetchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.FetchResponse buildPartial() {
      com.flexodbc.sidecar.proto.FetchResponse result = new com.flexodbc.sidecar.proto.FetchResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.flexodbc.sidecar.proto.FetchResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.batch_ = batchBuilder_ == null
            ? batch_
            : batchBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.flexodbc.sidecar.proto.FetchResponse) {
        return mergeFrom((com.flexodbc.sidecar.proto.FetchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.flexodbc.sidecar.proto.FetchResponse other) {
      if (other == com.flexodbc.sidecar.proto.FetchResponse.getDefaultInstance()) return this;
      if (other.hasBatch()) {
        mergeBatch(other.getBatch());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBatchFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.flexodbc.sidecar.proto.RowSet batch_;
    private com.google.protobuf.SingleFieldBuilder<
        com.flexodbc.sidecar.proto.RowSet, com.flexodbc.sidecar.proto.RowSet.Builder, com.flexodbc.sidecar.proto.RowSetOrBuilder> batchBuilder_;
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     * @return Whether the batch field is set.
     */
    public boolean hasBatch() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     * @return The batch.
     */
    public com.flexodbc.sidecar.proto.RowSet getBatch() {
      if (batchBuilder_ == null) {
        return batch_ == null ? com.flexodbc.sidecar.proto.RowSet.getDefaultInstance() : batch_;
      } else {
        return batchBuilder_.getMessage();
      }
    }
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     */
    public Builder setBatch(com.flexodbc.sidecar.proto.RowSet value) {
      if (batchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        batch_ = value;
      } else {
        batchBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     */
    public Builder setBatch(
        com.flexodbc.sidecar.proto.RowSet.Builder builderForValue) {
      if (batchBuilder_ == null) {
        batch_ = builderForValue.build();
      } else {
        batchBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     */
    public Builder mergeBatch(com.flexodbc.sidecar.proto.RowSet value) {
      if (batchBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          batch_ != null &&
          batch_ != com.flexodbc.sidecar.proto.RowSet.getDefaultInstance()) {
          getBatchBuilder().mergeFrom(value);
        } else {
          batch_ = value;
        }
      } else {
        batchBuilder_.mergeFrom(value);
      }
      if (batch_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     */
    public Builder clearBatch() {
      bitField0_ = (bitField0_ & ~0x00000001);
      batch_ = null;
      if (batchBuilder_ != null) {
        batchBuilder_.dispose();
        batchBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     */
    public com.flexodbc.sidecar.proto.RowSet.Builder getBatchBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBatchFieldBuilder().getBuilder();
    }
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     */
    public com.flexodbc.sidecar.proto.RowSetOrBuilder getBatchOrBuilder() {
      if (batchBuilder_ != null) {
        return batchBuilder_.getMessageOrBuilder();
      } else {
        return batch_ == null ?
            com.flexodbc.sidecar.proto.RowSet.getDefaultInstance() : batch_;
      }
    }
    /**
     * <code>.flexodbc.RowSet batch = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.flexodbc.sidecar.proto.RowSet, com.flexodbc.sidecar.proto.RowSet.Builder, com.flexodbc.sidecar.proto.RowSetOrBuilder> 
        internalGetBatchFieldBuilder() {
      if (batchBuilder_ == null) {
        batchBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.flexodbc.sidecar.proto.RowSet, com.flexodbc.sidecar.proto.RowSet.Builder, com.flexodbc.sidecar.proto.RowSetOrBuilder>(
                getBatch(),
                getParentForChildren(),
                isClean());
        batch_ = null;
      }
      return batchBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:flexodbc.FetchResponse)
  }

  // @@protoc_insertion_point(class_scope:flexodbc.FetchResponse)
  private static final com.flexodbc.sidecar.proto.FetchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.flexodbc.sidecar.proto.FetchResponse();
  }

  public static com.flexodbc.sidecar.proto.FetchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchResponse>() {
    @java.lang.Override
    public FetchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FetchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.flexodbc.sidecar.proto.FetchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

