// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public interface RowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flexodbc.Row)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Raw bytes for zero-copy parsing in C++ Host
   * </pre>
   *
   * <code>repeated bytes columns = 1;</code>
   * @return A list containing the columns.
   */
  java.util.List<com.google.protobuf.ByteString> getColumnsList();
  /**
   * <pre>
   * Raw bytes for zero-copy parsing in C++ Host
   * </pre>
   *
   * <code>repeated bytes columns = 1;</code>
   * @return The count of columns.
   */
  int getColumnsCount();
  /**
   * <pre>
   * Raw bytes for zero-copy parsing in C++ Host
   * </pre>
   *
   * <code>repeated bytes columns = 1;</code>
   * @param index The index of the element to return.
   * @return The columns at the given index.
   */
  com.google.protobuf.ByteString getColumns(int index);
}
