// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

@com.google.protobuf.Generated
public interface RowSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flexodbc.RowSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  java.util.List<com.flexodbc.sidecar.proto.Row> 
      getRowsList();
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  com.flexodbc.sidecar.proto.Row getRows(int index);
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  java.util.List<? extends com.flexodbc.sidecar.proto.RowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  com.flexodbc.sidecar.proto.RowOrBuilder getRowsOrBuilder(
      int index);

  /**
   * <code>bool has_more = 2;</code>
   * @return The hasMore.
   */
  boolean getHasMore();

  /**
   * <pre>
   * Standard ODBC SQLState for Error Mapping
   * </pre>
   *
   * <code>string sql_state = 3;</code>
   * @return The sqlState.
   */
  java.lang.String getSqlState();
  /**
   * <pre>
   * Standard ODBC SQLState for Error Mapping
   * </pre>
   *
   * <code>string sql_state = 3;</code>
   * @return The bytes for sqlState.
   */
  com.google.protobuf.ByteString
      getSqlStateBytes();

  /**
   * <code>string error_message = 4;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 4;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
