// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: driver.proto
// Protobuf Java Version: 4.34.1

package com.flexodbc.sidecar.proto;

/**
 * <pre>
 * Represents a batch of rows for the Zero-Copy &amp; minimal context-switch intent
 * </pre>
 *
 * Protobuf type {@code flexodbc.RowSet}
 */
@com.google.protobuf.Generated
public final class RowSet extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flexodbc.RowSet)
    RowSetOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "RowSet");
  }
  // Use RowSet.newBuilder() to construct.
  private RowSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RowSet() {
    rows_ = java.util.Collections.emptyList();
    sqlState_ = "";
    errorMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_RowSet_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_RowSet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_RowSet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.flexodbc.sidecar.proto.RowSet.class, com.flexodbc.sidecar.proto.RowSet.Builder.class);
  }

  public static final int ROWS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.flexodbc.sidecar.proto.Row> rows_;
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.flexodbc.sidecar.proto.Row> getRowsList() {
    return rows_;
  }
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.flexodbc.sidecar.proto.RowOrBuilder> 
      getRowsOrBuilderList() {
    return rows_;
  }
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  @java.lang.Override
  public int getRowsCount() {
    return rows_.size();
  }
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  @java.lang.Override
  public com.flexodbc.sidecar.proto.Row getRows(int index) {
    return rows_.get(index);
  }
  /**
   * <code>repeated .flexodbc.Row rows = 1;</code>
   */
  @java.lang.Override
  public com.flexodbc.sidecar.proto.RowOrBuilder getRowsOrBuilder(
      int index) {
    return rows_.get(index);
  }

  public static final int HAS_MORE_FIELD_NUMBER = 2;
  private boolean hasMore_ = false;
  /**
   * <code>bool has_more = 2;</code>
   * @return The hasMore.
   */
  @java.lang.Override
  public boolean getHasMore() {
    return hasMore_;
  }

  public static final int SQL_STATE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sqlState_ = "";
  /**
   * <pre>
   * Standard ODBC SQLState for Error Mapping
   * </pre>
   *
   * <code>string sql_state = 3;</code>
   * @return The sqlState.
   */
  @java.lang.Override
  public java.lang.String getSqlState() {
    java.lang.Object ref = sqlState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sqlState_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Standard ODBC SQLState for Error Mapping
   * </pre>
   *
   * <code>string sql_state = 3;</code>
   * @return The bytes for sqlState.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSqlStateBytes() {
    java.lang.Object ref = sqlState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sqlState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <code>string error_message = 4;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 4;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rows_.size(); i++) {
      output.writeMessage(1, rows_.get(i));
    }
    if (hasMore_ != false) {
      output.writeBool(2, hasMore_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sqlState_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, sqlState_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, errorMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = rows_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(rows_.get(i));
          }
          size += 1 * count;
        }
    if (hasMore_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hasMore_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sqlState_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, sqlState_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, errorMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.flexodbc.sidecar.proto.RowSet)) {
      return super.equals(obj);
    }
    com.flexodbc.sidecar.proto.RowSet other = (com.flexodbc.sidecar.proto.RowSet) obj;

    if (!getRowsList()
        .equals(other.getRowsList())) return false;
    if (getHasMore()
        != other.getHasMore()) return false;
    if (!getSqlState()
        .equals(other.getSqlState())) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRowsCount() > 0) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRowsList().hashCode();
    }
    hash = (37 * hash) + HAS_MORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasMore());
    hash = (37 * hash) + SQL_STATE_FIELD_NUMBER;
    hash = (53 * hash) + getSqlState().hashCode();
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.flexodbc.sidecar.proto.RowSet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.flexodbc.sidecar.proto.RowSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.flexodbc.sidecar.proto.RowSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.flexodbc.sidecar.proto.RowSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.flexodbc.sidecar.proto.RowSet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a batch of rows for the Zero-Copy &amp; minimal context-switch intent
   * </pre>
   *
   * Protobuf type {@code flexodbc.RowSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flexodbc.RowSet)
      com.flexodbc.sidecar.proto.RowSetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_RowSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_RowSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.flexodbc.sidecar.proto.RowSet.class, com.flexodbc.sidecar.proto.RowSet.Builder.class);
    }

    // Construct using com.flexodbc.sidecar.proto.RowSet.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
      } else {
        rows_ = null;
        rowsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      hasMore_ = false;
      sqlState_ = "";
      errorMessage_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.flexodbc.sidecar.proto.Driver.internal_static_flexodbc_RowSet_descriptor;
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.RowSet getDefaultInstanceForType() {
      return com.flexodbc.sidecar.proto.RowSet.getDefaultInstance();
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.RowSet build() {
      com.flexodbc.sidecar.proto.RowSet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.flexodbc.sidecar.proto.RowSet buildPartial() {
      com.flexodbc.sidecar.proto.RowSet result = new com.flexodbc.sidecar.proto.RowSet(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.flexodbc.sidecar.proto.RowSet result) {
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rows_ = rows_;
      } else {
        result.rows_ = rowsBuilder_.build();
      }
    }

    private void buildPartial0(com.flexodbc.sidecar.proto.RowSet result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hasMore_ = hasMore_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sqlState_ = sqlState_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.flexodbc.sidecar.proto.RowSet) {
        return mergeFrom((com.flexodbc.sidecar.proto.RowSet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.flexodbc.sidecar.proto.RowSet other) {
      if (other == com.flexodbc.sidecar.proto.RowSet.getDefaultInstance()) return this;
      if (rowsBuilder_ == null) {
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
      } else {
        if (!other.rows_.isEmpty()) {
          if (rowsBuilder_.isEmpty()) {
            rowsBuilder_.dispose();
            rowsBuilder_ = null;
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rowsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRowsFieldBuilder() : null;
          } else {
            rowsBuilder_.addAllMessages(other.rows_);
          }
        }
      }
      if (other.getHasMore() != false) {
        setHasMore(other.getHasMore());
      }
      if (!other.getSqlState().isEmpty()) {
        sqlState_ = other.sqlState_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.flexodbc.sidecar.proto.Row m =
                  input.readMessage(
                      com.flexodbc.sidecar.proto.Row.parser(),
                      extensionRegistry);
              if (rowsBuilder_ == null) {
                ensureRowsIsMutable();
                rows_.add(m);
              } else {
                rowsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              hasMore_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              sqlState_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.flexodbc.sidecar.proto.Row> rows_ =
      java.util.Collections.emptyList();
    private void ensureRowsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rows_ = new java.util.ArrayList<com.flexodbc.sidecar.proto.Row>(rows_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.flexodbc.sidecar.proto.Row, com.flexodbc.sidecar.proto.Row.Builder, com.flexodbc.sidecar.proto.RowOrBuilder> rowsBuilder_;

    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public java.util.List<com.flexodbc.sidecar.proto.Row> getRowsList() {
      if (rowsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rows_);
      } else {
        return rowsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public int getRowsCount() {
      if (rowsBuilder_ == null) {
        return rows_.size();
      } else {
        return rowsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public com.flexodbc.sidecar.proto.Row getRows(int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);
      } else {
        return rowsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder setRows(
        int index, com.flexodbc.sidecar.proto.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder setRows(
        int index, com.flexodbc.sidecar.proto.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder addRows(com.flexodbc.sidecar.proto.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder addRows(
        int index, com.flexodbc.sidecar.proto.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(index, value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder addRows(
        com.flexodbc.sidecar.proto.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder addRows(
        int index, com.flexodbc.sidecar.proto.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder addAllRows(
        java.lang.Iterable<? extends com.flexodbc.sidecar.proto.Row> values) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
      } else {
        rowsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder clearRows() {
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public Builder removeRows(int index) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.remove(index);
        onChanged();
      } else {
        rowsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public com.flexodbc.sidecar.proto.Row.Builder getRowsBuilder(
        int index) {
      return internalGetRowsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public com.flexodbc.sidecar.proto.RowOrBuilder getRowsOrBuilder(
        int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);  } else {
        return rowsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public java.util.List<? extends com.flexodbc.sidecar.proto.RowOrBuilder> 
         getRowsOrBuilderList() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rows_);
      }
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public com.flexodbc.sidecar.proto.Row.Builder addRowsBuilder() {
      return internalGetRowsFieldBuilder().addBuilder(
          com.flexodbc.sidecar.proto.Row.getDefaultInstance());
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public com.flexodbc.sidecar.proto.Row.Builder addRowsBuilder(
        int index) {
      return internalGetRowsFieldBuilder().addBuilder(
          index, com.flexodbc.sidecar.proto.Row.getDefaultInstance());
    }
    /**
     * <code>repeated .flexodbc.Row rows = 1;</code>
     */
    public java.util.List<com.flexodbc.sidecar.proto.Row.Builder> 
         getRowsBuilderList() {
      return internalGetRowsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.flexodbc.sidecar.proto.Row, com.flexodbc.sidecar.proto.Row.Builder, com.flexodbc.sidecar.proto.RowOrBuilder> 
        internalGetRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.flexodbc.sidecar.proto.Row, com.flexodbc.sidecar.proto.Row.Builder, com.flexodbc.sidecar.proto.RowOrBuilder>(
                rows_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }

    private boolean hasMore_ ;
    /**
     * <code>bool has_more = 2;</code>
     * @return The hasMore.
     */
    @java.lang.Override
    public boolean getHasMore() {
      return hasMore_;
    }
    /**
     * <code>bool has_more = 2;</code>
     * @param value The hasMore to set.
     * @return This builder for chaining.
     */
    public Builder setHasMore(boolean value) {

      hasMore_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_more = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasMore() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hasMore_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object sqlState_ = "";
    /**
     * <pre>
     * Standard ODBC SQLState for Error Mapping
     * </pre>
     *
     * <code>string sql_state = 3;</code>
     * @return The sqlState.
     */
    public java.lang.String getSqlState() {
      java.lang.Object ref = sqlState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sqlState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Standard ODBC SQLState for Error Mapping
     * </pre>
     *
     * <code>string sql_state = 3;</code>
     * @return The bytes for sqlState.
     */
    public com.google.protobuf.ByteString
        getSqlStateBytes() {
      java.lang.Object ref = sqlState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Standard ODBC SQLState for Error Mapping
     * </pre>
     *
     * <code>string sql_state = 3;</code>
     * @param value The sqlState to set.
     * @return This builder for chaining.
     */
    public Builder setSqlState(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sqlState_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Standard ODBC SQLState for Error Mapping
     * </pre>
     *
     * <code>string sql_state = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSqlState() {
      sqlState_ = getDefaultInstance().getSqlState();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Standard ODBC SQLState for Error Mapping
     * </pre>
     *
     * <code>string sql_state = 3;</code>
     * @param value The bytes for sqlState to set.
     * @return This builder for chaining.
     */
    public Builder setSqlStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sqlState_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 4;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 4;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:flexodbc.RowSet)
  }

  // @@protoc_insertion_point(class_scope:flexodbc.RowSet)
  private static final com.flexodbc.sidecar.proto.RowSet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.flexodbc.sidecar.proto.RowSet();
  }

  public static com.flexodbc.sidecar.proto.RowSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RowSet>
      PARSER = new com.google.protobuf.AbstractParser<RowSet>() {
    @java.lang.Override
    public RowSet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RowSet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RowSet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.flexodbc.sidecar.proto.RowSet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

